### ISSUE TITLE
Missing libsodium

### ISSUE THREAD

**Issue by izmntuk** [programthink/opensource#5]
![libsodium](https://raw.github.com/jedisct1/libsodium/master/logo.png)
Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more. It is a portable, cross-compilable, installable, packageable fork of [NaCl](https://github.com/jedisct1/libsodium), with a compatible API, and an extended API to improve usability even further. 

**Upstream:** <https://github.com/jedisct1/libsodium>
**License:** ISC
(FYI, NaCl was placed in public domain)

Projects that using libsodium or its binding:
[shadowsocks](https://github.com/shadowsocks/shadowsocks/)
[dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy)

**Comment by programthink** [comment]
@izmntuk 
多谢推荐项目（已加入）。
由于 libsodium 派生自 NaCl，俺顺便把 NaCl 也加入。
